[package]
name = "pecos-cli"
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "pecos"
path = "src/main.rs"

[dependencies]
pecos-engines = { workspace = true }
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"

[lints]
workspace = true
